footprint: [[-0.5, -0.33], [-0.5, 0.33], [0.5, 0.33], [0.5, -0.33]]
footprint_padding: 0.01

robot_base_frame: base_link
update_frequency: 5.0 # 代价地图更新频率
publish_frequency: 5.0 # 代价地图的发布频率
transform_tolerance: 0.5 # 等待坐标变换发布信息的超时时间

resolution: 0.05 # 地图的分辨率，单位是m，一般与静态地图分辨率保持一致

obstacle_range: 6.0 # 用于障碍物探测，比如：值为3.0，意味着检测到距离小于3米的障碍物时，就会引入代价地图
raytrace_range: 6.5 # 用于清除障碍物，比如：值为3.5，意味着清除代价地图中3.5米以外的障碍物

#layer definitions
# 静态地图层，SLAM构建的静态地图，基本上不变的图层
static:
    map_topic: /map
    subscribe_to_updates: true
# 障碍地图层，用于动态的记录传感器感知的障碍物信息
obstacles_laser:
    observation_sources: laser
    laser: {sensor_frame: velodyne, data_type: LaserScan, clearing: true, marking: true, topic: /front/scan, inf_is_valid: true}
# 膨胀层，在静态地图层和障碍地图层上进行膨胀，以避免机器人的外壳撞上障碍物
inflation:
    # 膨胀半径，扩展在碰撞区域以外的代价区域，使得机器人规划路径避开障碍物
    inflation_radius: 0.20